---
title: "Día 16 - Matrices"
author: "Dra. Norma C. Pérez Rosas"
date: '`r format(Sys.time(), "%d/%m/%Y")`'
output:
  pdf_document:
    toc: yes
    toc_depth: '2'
  html_document:
    toc: yes
    toc_depth: 2
---

# Propiedades algebráicas de las matrices

$$
\mathbf{A}-\mathbf{B} = (\mathbf{A})+(-\mathbf{B})
$$

```{python}
import numpy as np
# creando la primera matriz
A = np.array([[1, 2], [3, 4]])
# creando la segunda matriz
B = np.array([[4, 5], [6, 7]])
print("Imprimiendo la  matriz A")
print(A)
print("Imprimiendo la  matriz B")
print(B)
# restando dos matrices
print("Suma de matrices A - B")
print(np.subtract(A, B))
# sumando dos matrices
print("Suma de matrices (A + (-B)")
print(np.add(A, -1*B))
```

$$
\mathbf{A}-\mathbf{A} = \mathbf{0}
$$

```{python}
#creando la primera matriz
A = np.array([[1, 2], [3, 4]])
print("Imprimiendo la  matriz A")
print(A)
#restando dos matrices
print("Resta de matrices A-A")
print(np.subtract(A, A))
```

$$
\mathbf{A}+\mathbf{0} = \mathbf{A}
$$

```{python}
#creando la primera matriz
A = np.array([[1, 2], [3, 4]])
print("Imprimiendo la  matriz A")
print(A)
CEROS = np.array([[0, 0], [0, 0]])
print("Imprimiendo la  matriz de ceros")
print(CEROS)
#restando las dos matrices A + CEROS
print("Resta de matrices A + CEROS")
print(np.subtract(A, CEROS))
```

La transpuesta de la suma de dos o más matrices es la suma de las transpuestas de matrices individuales:

$$
(\mathbf{A}+\mathbf{B})^{T} = \mathbf{A}^T+\mathbf{B}^T
$$

```{python}
#lado izquierdo
import numpy as np
A = np.array([[1, 2, 3], [4, 5, 6]])
print(A)
B = np.array([[2, 1, 5], [4, 3, 8]])
print(B)
suma_A_B = np.add(A, B)
print(suma_A_B) 
suma_A_B_transpuesta = np.transpose(suma_A_B)
print(suma_A_B_transpuesta)
```

```{python}
#lado izquierdo
import numpy as np
A = np.array([[1, 2, 3], [4, 5, 6]])
print(A)
A_transpuesta = np.transpose(A) 
B = [[2, 1, 5], [4, 3, 8]]
print(B)
B_transpuesta = np.transpose(B)
print(B_transpuesta) 
suma_A_B_transpuestas = np.add(A_transpuesta, B_transpuesta)
print(suma_A_B_transpuestas)
```

La suma de dos matrices triangulares inferiores o superiores es también una matriz superior o inferior.

$$
\mathbf{A}=\left[
\begin{array}{cccc}
   7 & 0 & 0 & 0 \\
   1 & 4 & 0 & 0 \\
   9 & 2 & 3 & 0\\
   4 & 9 & 8 & 5\\
\end{array}
\right]
$$

$$
\mathbf{B}=\left[
\begin{array}{cccc}
   4 & 0 & 0 & 0 \\
   3 & 5 & 0 & 0 \\
   9 & 7 & 8 & 0\\
   2 & 4 & 9 & 2\\
\end{array}
\right]
$$

```{python}
#lado izquierdo
import numpy as np
A = np.array([[7, 0, 0, 0], [1, 4, 0, 0], [9, 2, 3, 0], [4, 9, 8, 5]])
B = np.array([[4, 0, 0, 0], [3, 5, 0, 0], [9, 7, 8, 0], [2, 4, 9, 2]])
suma_A_B = np.add(A, B)
print(suma_A_B)
```

# Multiplicación de una matriz por un escalar

Dado un escalar $k$ y una matriz $\mathbf{A}$, el producto $k\mathbf{A}$ es obtenido al multiplicar cada entrada de $\mathbf{A}$ por $k$, que es:

$(k\mathbf{A})_{ij}=ka_{ij}$

Ejemplo:

Si $k=-2$ y

$$
\mathbf{A}=\left[
\begin{array}{cc}
1 & 2  \\
3 & 4  \\
\end{array}
\right]
$$

Entonces

$$
k\mathbf{A}=\left[
\begin{array}{cc}
-2 & -4  \\
-6 & -8  \\
\end{array}
\right]
$$

```{python}
import numpy as np
k = -2
A = np.array([[1, 2], [3, 4]])
mult_k_A = k * A
print(mult_k_A)
```

La transpuesta de una matriz que ha sido multiplicada por un un escalar es:

$(k\mathbf{A})^T=k\mathbf{A}^T$

```{python}
import numpy as np
k = -2
A = np.array([[1, 2], [3, 4]])
mult_k_A = k * A
print(mult_k_A)
mult_k_A_transpuesta = np.transpose(mult_k_A)
print(mult_k_A_transpuesta)
A_transpuest = np.transpose(A) 
mult_k_A_trans = k * A_transpuest
print(mult_k_A_trans)
```

# Multiplicación de una matriz

La adición de una matriz puede sugerir que multiplicar dos matrices involucra la multiplicación de las entradas correspondientes. Sin embargo, este no es el caso y la experiencia muestra que un método más complejo pero un método menos intuitivo es más apropiado. Una clave de cómo multiplicar matrices fue dado cuando se introdujo el producto interno. El producto punto fue descrito en términos de multiplicar un vector fila, por un vector columna:

```{=tex}
\begin{equation*}
\mathbf{x}^T\mathbf{y} = [x_1 x_2 \dots x_n]
\begin{pmatrix}
y_1  \\
y_2 \\
\vdots   \\
y_n 
\end{pmatrix} = x_1y_1 + x_2y_2 \cdots x_ny_n
\end{equation*}
```


La aproximación tomada para calcular el producto interno puede ser naturalmente extendido para incluir múltiples filas y columnas de forma tal que la multiplicación ocurra sobre en una fila basada en una columna. Esta aproximación también requiere que el número de columnas de la primera matriz sea igual al número de filas de la segunda matriz. Las otras dimensiones determinan el tamaño del producto final. El elemento, $ij$ de un producto de una matriz es dado por:

$(\mathbf{AB})_{ij}=x_{i1}y_{1j}+x_{i2}y_{2j}+\cdots+x_{in}y_{nj}$

Reglas para la multiplicación de matrices: las dimensiones internas deben de coincidir $(n=n)$, el número de filas en la primera matriz $(m)$ determina el número de filas en el producto, mientras que el número de columnas en la segunda matriz $(p)$ determina el número de columnas en el producto.

$(m \times n)\cdot(n\times p)=(m\times p)$

![Reglas para la multiplicación de matrices. Las dimensiones de las columnas de la primera matriz deben ser iguales a las dimensiones de las filas de la segunda matriz n=n, el número de filas de la primera matriz (m) determina el número de filas en el producto mientras el número de columnas de la segunda matriz (p) determina el número de columans en el prodcuto.](multiplicacion_matriz.png)

La forma en que definimos una multiplicación significa que en general la multiplicación de matrices no es conmutativa, esto es los productos $\mathbf{AB}$ y $\mathbf{BA}$ son usualmente diferentes. Sin embargo, la multiplicación de matrices obedece la leyes asociativas y distributivas.

$$
\mathbf{A}(\mathbf{B}\mathbf{C}) = (\mathbf{A}\mathbf{B})\mathbf{C}
$$

```{python}
#lado izquierdo
import numpy as np
A = np.array([[1, 2, 3], [4, 5, 6]])
print(A)
B = np.array([[2, 1, 5, 4], [4, 3, 8, 6], [7, 8, 9, 9]])
print(B)
C = np.array([[1, 5, 9], [2, 6, 10], [7, 3, 11], [4, 8, 12]])
print(C)
mult_B_C = np.matmul(B, C)
print(mult_B_C)
mult_A_mult_B_C = np.matmul(A, mult_B_C) 
print(mult_A_mult_B_C)
```


```{python}
#lado derecho
import numpy as np
A = np.array([[1, 2, 3], [4, 5, 6]])
print(A)
B = np.array([[2, 1, 5, 4], [4, 3, 8, 6], [7, 8, 9, 9]])
print(B)
C = np.array([[1, 5, 9], [2, 6, 10], [7, 3, 11], [4, 8, 12]])
print(C)
mult_A_B = np.matmul(A, B)
print(mult_A_B)
mult_A_B_mult_C = np.matmul(mult_A_B, C) 
print(mult_A_B_mult_C)
```



# Asistencia 

From Irving Barreto to Everyone:  11:31 AM

Presente

From Melanie Mondragón to Everyone:  11:31 AM

presente

From Fernanda Pilón to Everyone:  11:32 AM

Presente :)

From David Dorantes to Everyone:  11:35 AM

Presente

From Jorge Ambrosio to Everyone:  11:35 AM

Presente

From Itzel Aurora Bravo Santos to Everyone:  11:35 AM

Presente

From Emmanuel Gonzalez to Everyone:  11:35 AM

Presente

From Maria Fernanda Garcia to Everyone:  11:35 AM

Presente

From Diego Nicolas to Everyone:  11:35 AM

Presente

From Andrew Flores Yebra to Everyone:  11:35 AM

Presente

From Frida Cuevas to Everyone:  11:35 AM

Presente

From Wenddy Ballona Martinez to Everyone:  11:36 AM

presente

From Gaeta to Everyone:  11:36 AM

Presente

From JOSE MARIA GARDUÑO VELAZQUEZ to Everyone:  11:36 AM

PRESENTE

From Víctor Jerónimo to Everyone:  12:13 PM

Presente

From Pérez David to Everyone:  12:13 PM

Presente

From Wenddy Ballona Martinez to Everyone:  01:33 PM

presente

From Karla Gómez to Everyone:  01:34 PM

Presente

From Diego Nicolas to Everyone:  01:34 PM

presente



