---
title: "Día 12 -1er. Examen - Álgebra Lineal"
author: "Dra. Norma C. Pérez Rosas"
date: '`r format(Sys.time(), "%d/%m/%Y")`'
output:
  pdf_document:
    toc: yes
    toc_depth: '2'
  html_document:
    toc: yes
    toc_depth: 2
---

Instrucciones: responda correctamente las siguientes preguntas. Valor por acierto (3.6 puntos). Al terminar tome fotografía a sus respuestas, genere un solo PDF con la siguiente estructura apellido_paterno_apellido_materno_nombre_examen1_grupo.pdf y envíe su examen al classroom.

Al inicio de su examen coloque 

**Nombre completo**

**Grupo**

**Boleta**

**correo electrónico**

1. Un **vector** es:

una lista ordenada de números y está descrito por:

\begin{equation*}
\mathbf{v} = 
\begin{pmatrix}
v_1 \\
v_2\\
\vdots \\
v_n \\
\end{pmatrix}
\end{equation*}


2. Un vector puede ser escrito horizontalmente (es decir, cuando los elementos del vector están colocados uno al lado de otro) en un vector **fila**  o verticalmente (cuando los elementos son colocado uno abajo de otro) en un vector **columna**. Sí el contexto es ambiguo se asume que el vector es un vector **columna**. El $i-ésimo$ elemento de un vector $v$ es denotado por  $v_i$. 

3. La **transpuesta**  de un vector columna es un vector fila de la misma longitud. La **transpuesta**  de un vector fila es un vector columna. En matemáticas, la **transpuesta**  está denotada por el superíndice $T$. 

4. Un vector de **ceros**  es un vector en $R^n$ cuyos elementos son todos ceros. 

5. La **magnitud** de un vector es la medida de su longitud y está definida como: $|\mathbf{v}|=\sqrt{v_1^2+v_2^2+\dots v_n^2}$

6. Sí $P = [3, -4]$ y $Q = [8, 6]$, el vector $\vec{PQ}$ tiene longitud:

a) $|3|+|-4|$

b) $(3)^2+(-4)^2|$

c) $(3-8)^2+(-4-6)^2$

**d)** $\sqrt{(8-3)^2+(6-(-4))^2}$


7. La dirección del vector $[4,8]$ es:______

a) $\pi$

b) $\tan^{-1}(8 -4)$

c) $\frac{8}{4}\pi$

**d)** $\tan^{-1}(8/4)$

8. Si $\mathbf{u}=[4,3]$, entonces el vector unitario con la misma dirección que $\mathbf{u}$ es:

```{r, echo = FALSE}
etiquetas <- c('u')
xlim <- c(0,7)
ylim <- c(-2,5)
plot( xlim, ylim, type="n", xlab="x", ylab="y", asp=1)
arrows(0,0,4,3, col = 'red' )
text(c(2),etiquetas,col = c("red"))
abline(v=0, h=0, col = 'gray' )
```

a) $(0.4, 0.3)$

b) $(0.8,0.6)$

**c)** $(\frac{4}{5}, \frac{3}{5})$

Justificación

$|\mathbf{v}|=\sqrt{4^2+3^2}=\sqrt{16+9}=\sqrt{25}=5$

El vector de magnitud unitaria es dividir las coordenas por la magnitud de v: 

$(\frac{4}{5}, \frac{3}{5})$


9. Sean $\mathbf{u}$ y $\mathbf{v}$ dados por


\begin{equation*}
\mathbf{u} = 
\begin{pmatrix}
\sqrt{2}  \\
1 \\
-1 \\
\end{pmatrix}
\end{equation*}

\begin{equation*}
\mathbf{v} = 
\begin{pmatrix}
0  \\
2 \\
-2 \\
\end{pmatrix}
\end{equation*}

la distancia entre ellos estaría dada por 

a)
\begin{equation*}
\mathbf{u-v} = 
\begin{pmatrix}
\sqrt{2}  \\
-1 \\
1 \\
\end{pmatrix}
\end{equation*}



b)
\begin{equation*}
\mathbf{u+v} = 
\begin{pmatrix}
\sqrt{2}  \\
3 \\
-2 \\
\end{pmatrix}
\end{equation*}



**c)** $\sqrt{(\sqrt{2})^2+(-1)^2+1^2}$

Justificación 

$$
\mathbf{u}-\mathbf{v}=\left[
\begin{array}{c}
\sqrt{2}\\
1 \\
-1 \\
\end{array}
\right]-\left[
\begin{array}{c}
0\\
2\\
-2\\
\end{array}
\right]=\left[
\begin{array}{c}
\sqrt{2}\\
-1 \\
1 \\
\end{array}
\right]
$$
$|\mathbf{u}-\mathbf{v}|=\sqrt{(\sqrt2)^2+(-1)^2+1^2}$

d) $\mathbf{u}^T\mathbf{v}$

10. $\mathbf{0} \cdot \mathbf{v}=$

\begin{equation*}
\mathbf{0}^T\mathbf{v} = [0 \ 0 \dots 0]
\begin{pmatrix}
v_1  \\
v_2 \\
\vdots   \\
v_n 
\end{pmatrix}
\end{equation*}

$\mathbf{0}^T\mathbf{v}=[0*v_1+0*v_2+....+0*v_n]=0$



11. Sí $\mathbf{u}$, $\mathbf{v}$ y $\mathbf{w}$ son vectores en $\mathbf{R}^n$, con $n\geq2$ y c es un escalar explique ¿por qué las siguientes expresiones no tienen sentido?

a) $c^T(\mathbf{u}+\mathbf{v})$
 
No se puede calcular la transpuesta de un escalar $c^T$. 

b) $\mathbf{u}^T(\mathbf{v}^T\mathbf{w})$


\begin{equation*}
\mathbf{u} = 
\begin{pmatrix}
u_{1}  \\
u_{2} \\
\vdots   \\
u_{n} 
\end{pmatrix}
\end{equation*}

\begin{equation*}
\mathbf{v} = 
\begin{pmatrix}
v_{1}  \\
v_{2} \\
\vdots   \\
v_{n} 
\end{pmatrix}
\end{equation*}

\begin{equation*}
\mathbf{w} = 
\begin{pmatrix}
w_{1}  \\
w_{2} \\
\vdots   \\
w_{n} 
\end{pmatrix}
\end{equation*}

\begin{equation*}
\mathbf{v}^T\mathbf{w} = [v_1 \ v_2 \dots v_3]
\begin{pmatrix}
w_1  \\
w_2 \\
\vdots   \\
w_n 
\end{pmatrix}=v_1w_1+v_2w_2+ \dots + v_nw_n = c
\end{equation*}


\begin{equation*}
\mathbf{u}^T(\mathbf{v}^T\mathbf{w})=\mathbf{u}^T(c)=? 
\end{equation*}

No se puede aplicar la definición de producto punto a $\mathbf{u}^T(c)$


12. Marque cuál se las siguientes oraciones es verdadera o falsa. Justifique su respuesta. 

a) Para los vectores $\mathbf{u}$, $\mathbf{v}$ y $\mathbf{w}$ en $R^n$, si $\mathbf{u} + \mathbf{v} = \mathbf{v} + \mathbf{w}$ entonces $\mathbf{u}=\mathbf{v}$

Falsa, sí  $\mathbf{u} + \mathbf{v} = \mathbf{v} + \mathbf{w}$ entonces $\mathbf{u}=\mathbf{w}$.


```{python}
#Si u = w 
import numpy as np
u = np.array([1, 1])
v = np.array([2, 2])
w = np.array([1, 1])
#lado izquierdo 
r1 = np.add(u,v)
print(r1)
#lado derecho 
r2 = np.add(v,w)
print(r2)
```
```{python}
#Si u = v 
import numpy as np
u = np.array([1, 1])
v = np.array([1, 1])
w = np.array([2, 2])
#lado izquierdo 
r1 = np.add(u,v)
print(r1)
#lado derecho 
r2 = np.add(v,w)
print(r2)
```
Por lo tanto, se concluye que $\mathbf{u}=\mathbf{w}$ para que se satisfaga la igualdad. 


b) Para los vectores $\mathbf{u}$, $\mathbf{v}$ y $\mathbf{w}$ en $R^n$, si $\mathbf{u}^T \mathbf{w} = \mathbf{v}^T\mathbf{w}$ entonces $\mathbf{u}=\mathbf{v}$ 

\begin{equation*}
\mathbf{u} = 
\begin{pmatrix}
1  \\
1 \\
\end{pmatrix}
\end{equation*}

\begin{equation*}
\mathbf{v} = 
\begin{pmatrix}
1  \\
1 \\
\end{pmatrix}
\end{equation*}

\begin{equation*}
\mathbf{w} = 
\begin{pmatrix}
2  \\
2 \\
\end{pmatrix}
\end{equation*}

\begin{equation*}
\mathbf{u}^T\mathbf{w} = [1 \ 1 ]
\begin{pmatrix}
2  \\
2 \\
\end{pmatrix}=(1)(2)+(1)(2) = 2+2=4
\end{equation*}


\begin{equation*}
\mathbf{v}^T\mathbf{w} = [1 \ 1 ]
\begin{pmatrix}
2  \\
2 \\
\end{pmatrix}=(1)(2)+(1)(2) = 2+2=4
\end{equation*}

Verdadero.

```{python}
#Si u = v 
import numpy as np
u = np.array([1, 1])
v = np.array([1, 1])
w = np.array([2, 2])
#lado izquierdo 
r1 = np.dot(u,w)
print(r1)
#lado derecho 
r2 = np.dot(v,w)
print(r2)
```
En caso de que $\mathbf{u}=\mathbf{w}$, no se cumple la igualdad. 
```{python}
#Si u = w 
import numpy as np
u = np.array([1, 1])
v = np.array([2, 2])
w = np.array([1, 1])
#lado izquierdo 
r1 = np.dot(u,w)
print(r1)
#lado derecho 
r2 = np.dot(v,w)
print(r2)
```


13. ¿Cuál de estos pares de vectores son ortogonales? Justifique su respuesta.

**a)** $[1,1]$, $[1,-1]$ 

Solución:

Para comprobar que dos vectores son ortogonales se debe calcular el producto punto, sí este es igual a cero, se concluye que el par de vectores son ortogonales.

\begin{equation*}
\mathbf{v}^T\mathbf{w} = [1 \ 1]
\begin{pmatrix}
1  \\
-1 \\
\end{pmatrix}=(1)(1)+(1)(-1) = 0
\end{equation*}

```{python}
import numpy as np
u = np.array([1, 1])
v = np.array([1, -1])
w = np.dot(u,v)
print(w)
```


Como el producto punto es cero, los vectores son ortogonales.

**b)** $[1, -1, -1]$, $[0,1,-1]$

Solución:

Para comprobar que dos vectores son ortogonales se debe calcular el producto punto, sí este es igual a cero, se concluye que el par de vectores son orgonales.

\begin{equation*}
\mathbf{v}^T\mathbf{w} = [1 \ -1 \ -1]
\begin{pmatrix}
0  \\
1 \\
-1 \\
\end{pmatrix}=(1)(0)+(-1)(1)+(-1)(-1) = 0
\end{equation*}

```{python}
import numpy as np
u = np.array([1, -1, -1])
v = np.array([0, 1, -1])
w = np.dot(u,v)
print(w)
```


Como el producto punto es cero, los vectores son ortogonales. 


14. Sean $\mathbf{u}=[-1,2,-2]$, $\mathbf{v}=[4,-3,5]$ y $\mathbf{w}=[-4,-2,0]$. Realice las siguientes operaciones

a) $\mathbf{u} \times \mathbf{v}$

$w_1=u_2v_3-u_3v_2=(2)(5)-(-2)(-3)=10-6=4$

$w_2=u_3v_1-u_1v_3=(-2)(4)-(-1)(5)=-8+5=-3$

$w_3=u_1v_2-u_2v_1=(-1)(-3)-(2)(4)=3-8=-5$

$\mathbf{u} \times \mathbf{v}=[4, -3, -5]$

```{python}
import numpy as np
u = np.array([-1, 2, -2])
v = np.array([4, -3, 5])
w = np.cross(u,v)
print(w)
```

b) $\mathbf{u} + (\mathbf{v} \times \mathbf{w})$

$z_1=v_2w_3-v_3w_2=(-3)(0)-(5)(-2)=0+10=10$


$z_2=v_3w_1-v_1w_3=(5)(-4)-(4)(0)=-20-0=-20$


$z_3=v_1w_2-v_2w_1=(4)(-2)-(-3)(-4)=-8-12=-20$

$\mathbf{z} = \mathbf{v} \times \mathbf{w}=[10, -20, -20]$


$$
\mathbf{u}+\mathbf{z}=\left[
\begin{array}{c}
-1\\
2 \\
-2 \\
\end{array}
\right]+\left[
\begin{array}{c}
10\\
-20 \\
-20 \\
\end{array}
\right]=\left[
\begin{array}{c}
9\\
-18 \\
-22 \\
\end{array}
\right]
$$


```{python}
import numpy as np
u = np.array([-1, 2, -2])
v = np.array([4, -3, 5])
w = np.array([-4, -2, 0])
z = np.cross(v,w)
print(z)
u_mas_z = np.add(u,z)
print(u_mas_z)
```


15. ¿Cuál de las siguientes expresiones están indefinidas?

a)

$\mathbf{u} \times \mathbf{u} \times \mathbf{u}$

```{python}
import numpy as np
u = np.array([2, 1, -2])
w = np.cross(u, np.cross(u, u))
print(w)
```


b) $\mathbf{u} \times \mathbf{v} \times \mathbf{w}$

```{python}
import numpy as np
u = np.array([2, 1, -2])
v = np.array([-4, -2, 0])
w = np.array([2, 1, -2])
w = np.cross(u, np.cross(v, w))
print(w)
```


